# Generated by Django 5.2.5 on 2025-08-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва класу')),
                ('year', models.IntegerField(verbose_name='Рік навчання')),
                ('number_of_students', models.IntegerField(default=0, verbose_name='Кількість учнів')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва предмету')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('credits', models.IntegerField(default=1, verbose_name='Кількість годин на тиждень')),
                ('is_core', models.BooleanField(default=True, verbose_name='Основний предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адреса')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_schedule.schoolclass', verbose_name='Клас')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Оцінка')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар вчителя')),
                ('is_final', models.BooleanField(default=False, verbose_name='Підсумкова оцінка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_schedule.student', verbose_name='Учень')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_schedule.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Років стажу')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_schedule.subject', verbose_name='Предмет')),
            ],
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_schedule.teacher', verbose_name='Класний керівник'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20, verbose_name='День тижня')),
                ('time', models.TimeField(verbose_name='Час початку')),
                ('room_number', models.CharField(blank=True, max_length=10, verbose_name='Номер аудиторії')),
                ('duration_minutes', models.IntegerField(default=45, verbose_name='Тривалість заняття')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_schedule.schoolclass', verbose_name='Клас')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_schedule.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_schedule.teacher', verbose_name='Вчитель')),
            ],
        ),
    ]
